# Basic
title: æç‘ç¥¥-ä¸ªäººåšå®¢-linuxçˆ±å¥½è€…
subtitle: ä¸ªäººå°é»‘å±‹
description: æ¬¢è¿æ¥åˆ°æˆ‘çš„ä¸ªäººå°é»‘å±‹~
# å¤´åƒé‡Œé¢çš„æ ‡é¢˜
avatarTitle: linuxè¿ç»´
# å¤´åƒé‡Œé¢çš„æè¿°
avatarDesc: linux / ç³»ç»Ÿå­¦ä¹ 
url: "http://lisirlinux.cn"

# Comment
comment:
    #disqus: leopard
    # gitment: xxx // éœ€è¦ä¿®æ”¹ comments.htmlä¸­çš„client_idå’Œclient_secret
    # uyan: 2143225  # æœ‰è¨€id,ç™»å½•æœ‰è¨€å®˜ç½‘ç”³è¯·

# Social
social:
    weibo: 5366874726 
    #github: lisir1010
    # zhihu: panpanleopard
    #juejin: xxx
    jianshu: 2ada30d8d0f7
    # twitter: 
    mail: lisir1010@163.com


# ç™¾åº¦ç»Ÿè®¡ 
# ä½¿ç”¨åšå®¢æ¨¡æ¿è¯·å»æ‰æˆ–è€…æ›´æ¢ id 
baidu:
    id: 96377f37d8f9a11cce937a6d289a19d6  


# ã€Š----------------- ä¸Šé¢çš„ä¿¡æ¯ä¿®æ”¹æˆä½ è‡ªå·±çš„ ---------------------------ã€‹
#
#
#  _post/ ä¸‹çš„æ–‡ç« æ›´æ¢æˆä½ è‡ªå·±çš„æ–‡ç« 
#  å¸®å¿™starä¸€ä¸‹ï¼Œæ„Ÿè°¢~ğŸ˜† åœ°å€ï¼š https://github.com/leopardpan/leopardpan.github.io
#
#
# ã€Š--------------- ä¸‹é¢çš„ä¿¡æ¯å¯ä»¥è‡ªè¡Œé€‰æ‹©æ˜¯å¦ä¿®æ”¹ ------------------------ã€‹


permalink: /:year/:month/:title/
# Format
highlighter: rouge

textColor: #FF0000

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: clear

# The blog button should not be removed.
blog_button:
    title: åšå®¢ä¸»é¡µ

# Navigation buttons in the front page.s
nav:
    - {title: æ‰€æœ‰æ–‡ç« , description: archive, url: '/archive'}   
    - {title: æ ‡ç­¾, description: tags, url: '/tags'}      
    - {title: å…³äºæˆ‘, description: about, url: '/about'}      
    

# Pagination
gems: [jekyll-paginate,jekyll-sitemap]
paginate: 20
paginate_path: "page/:num/"



theme: jekyll-theme-slate
